### ISSUE TITLE
wget -q https://github.com/YeongHyeon/NeuralFilter/raw/main/misc/matrices.zip

### ISSUE THREAD

**Issue by tianxinger** [YeongHyeon/RIAD-PyTorch#1]
Sorry to bother you, I have a question for you.The Matrices .zip file can't be found on GitHub now. I would like to ask the author if you still have this package.

**Comment by YeongHyeon** [comment]
Hi, @tianxinger 

I just updated the error you encountered.
The package on the error log is not related to this repository, but it seems to be a mix of exercises.
Can you try running it again and let me know if it works?

Thank you for your interest.

**Comment by tianxinger** [comment]
Hi, @YeongHyeon


Now it can run normally.




Thank you for your reply.










At 2023-03-08 21:35:59, "YeongHyeon Park" ***@***.***> wrote:

Hi, @tianxinger

I just updated the error you encountered.
The package on the error log is not related to this repository, but it seems to be a mix of exercises.
Can you try running it again and let me know if it works?

Thank you for your interest.

**Comment by tianxinger** [comment]
Hi, @YeongHyeon/RIAD-PyTorch 



Now it can run normally.I'm curious about where the mistake happened. Can you tell me where it is？


Thank you very much.














At 2023-03-08 21:35:59, "YeongHyeon Park" ***@***.***> wrote:

Hi, @tianxinger

I just updated the error you encountered.
The package on the error log is not related to this repository, but it seems to be a mix of exercises.
Can you try running it again and let me know if it works?

Thank you for your interest.
